sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t alexeyv1/docker -f Dockerfile.dev .

script:
  - docker run -e CI=true alexeyv1/docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-613632957754"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"